### ISSUE TITLE
Playing HD BBC recorded content defaults to audio-descriptions audio stream

### ISSUE THREAD

**Issue by 8none1** [oakesville/mythling#87]
When playing back recorded HD content to the Fire TV Stick the internal player is defaulting to the audio-descriptions audio channel rather than the 5.1 or stereo channels.

I didn't see an option to change this, so reporting it here.

I can provide example content if needed.

**Comment by 8none1** [comment]
Playing with VLC on the Fire TV Stick is the same, it too plays the Audio Descriptions channel.

Also, play the stream with VLC 2.2.2 on Ubuntu is selects the "NAR" track by default too - but  I can change it on the desktop app: (http://imgur.com/a/oTQOR

Codec information (screenshot)  http://imgur.com/a/oTQOR
vlc -vvv info (see line 172 for where it sees the NAR channel) :  http://paste.ubuntu.com/23613127/  


The file is an MPEG TS stream from DVB-T2.
It looks like the Audio Descriptions audio stream is the first of two audio streams in the file, and so I assume it's defaulting to the first one.  However, the stream ID values should probably be used here.    Specifically, the "NAR" stream (audio descriptions) is ID 5002 and the normal channel is stream 2, but ID 5001.  The video stream is ID 5000.

Upload a sample to:  http://www.whizzy.org/Planet.cut.mpg


This was just a raw chop from the original done with dd, so there will probably be some stream info missing from the start of the file, but I've tested it here and it seems to work and exhibit the issue.  You can hear the descriptions in the opening titles.

**Comment by oakesville** [comment]
Thanks for reporting this and providing the sample.  Correctly detecting the default audio track I believe is the job of LibVLC.

However, for Fire TV I've at least added the ability in Mythling to change the selected audio track:
https://github.com/oakesville/mythling/wiki/Mythling-On-Fire-TV#user-content-remote-buttons

This will be included in the next release.  In the meantime I've published this change to the Live App Testing channel, so if you're eager to try it out you can enroll as described under option 2 here:
https://github.com/oakesville/mythling/wiki/Mythling-On-Fire-TV#user-content-installation

I'm not closing this yet since I haven't decided how to expose audio track selection on mobile devices (i.e. other than Fire TV).

 - Don

**Comment by 8none1** [comment]
Fixed in 2.1.08.

I can confirm that 2.1.08 and the "middle-down-down" gesture on the remote allows me to cycle audio tracks and get the non-audio-descriptions version.

Thank you very much!
