### ISSUE TITLE
JSONException in parseMythTvSetting

### ISSUE THREAD

**Issue by wrsturm** [oakesville/mythling#92]
When looking up VideoStartupDir.  I think it tries to create a JSONObject from the xml expecting a SettingList but there is no such item.  The same for settings.  What is returned from the api lookup is just a bare \<String>directory path\</String>
eg \<?xml version="1.0" encoding="UTF-8"?>\<String>/anime1/Downloads\</String>
mythtv version is git master
Selection from the menu is for Videos

**Comment by oakesville** [comment]
If you're hitting this code, it appears that you don't have the "Videos" storage group set up.  I abandoned support for videos without the storage group when this was rejected:
https://code.mythtv.org/trac/ticket/12250#ticket
The legacy code is still in place, but from what you describe, it looks like it wouldn't work anymore due to API changes in GetSetting.

In short, to use Mythling you'll have to set up storage groups as described here:
https://github.com/oakesville/mythling/wiki

**Comment by wrsturm** [comment]
Thanks.  That gets the list of videos, but they don't play.  It seems that somewhere along the line the ip address has disappeared from the MRL.
11-16 22:42:46.732 11253-11322/? E/HttpHelper: http://:6544/Content/AddVideoLiveStream?Id=665&Height=480&Bitrate=600000&AudioBitrate=64000
11-16 22:42:46.732 11253-11322/? E/MediaActivity: http://:6544/Content/AddVideoLiveStream?Id=665&Height=480&Bitrate=600000&AudioBitrate=64000

**Comment by wrsturm** [comment]
Never mind.  needed a rescan on the backend.
